feat: Roads redesign v2
decentraland/unity-explorer pull request #1105
Opened 2024-05-13 20:38 UTC by Kinerius

## What does this PR change?

...

## How to test the changes?

1. Launch the explorer
2. ...

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

2024-05-15 23:14 UTC, olavra commented
Tested and looking good for me

2024-05-17 11:57 UTC, meshr00m commented
Ready to test and merge, added description on top!

2024-05-17 16:30 UTC, anicalbano approved these changes
Looks like the assets names are still the same as main:

![image](https://github.com/decentraland/unity-explorer/assets/139157886/906a7584-9021-4e8a-ae6b-c61bbba6871f)

2024-05-20 13:29 UTC, anicalbano approved these changes
🟢 Approved on the QA side

- There are no crashes
- Roads are working as expected

https://github.com/decentraland/unity-explorer/assets/139157886/fa1f3ab4-1205-4be5-8b2f-2995f071cf64



https://github.com/decentraland/unity-explorer/assets/139157886/739c9fd5-2fdc-4b37-831e-dbd4247aca8e

2024-05-20 13:49 UTC, m3taphysics requested changes

2024-05-20 13:49 UTC, m3taphysics commented on Explorer/Assets/DCL/PluginSystem/Global/LandscapePlugin.cs
> +            //LandscapeMiscCullingSystem.InjectToWorld(ref builder, landscapeData.Value, terrainGenerator);
Is this right?

2024-05-20 14:33 UTC, Kinerius commented on Explorer/Assets/DCL/PluginSystem/Global/LandscapePlugin.cs
> +            //LandscapeMiscCullingSystem.InjectToWorld(ref builder, landscapeData.Value, terrainGenerator);
It is

2024-05-20 16:05 UTC, merged