feat: Frame budgeting
decentraland/unity-explorer pull request #117
Opened 2023-07-21 19:40 UTC by dalkia

2023-07-27 08:20 UTC, mikhail-dcl requested changes

2023-07-27 08:20 UTC, mikhail-dcl commented on Explorer/Assets/Scripts/ECS/Profiling/Systems/ProfilerWindowSystem.cs
> +    public partial class ProfilerWindowSystem : BaseUnityLoopSystem
You call it a system but it does not behave as a system

2023-07-27 08:20 UTC, mikhail-dcl commented on Explorer/Assets/Scripts/ECS/Profiling/Systems/ProfilerWindowSystem.cs
> +        private async UniTaskVoid UpdateView(CancellationToken ct)
It's very strange: you should have this logic in `Update` function. Also this way you're hiding the impact of the system from `Profiler`

2023-07-27 08:20 UTC, mikhail-dcl commented on Explorer/Assets/Scripts/ECS/Profiling/ProfilingProvider.cs
> +        private async UniTaskVoid CountHiccup()
It should be handled in a system. Only systems are authorized to have loops like this

2023-07-27 08:20 UTC, mikhail-dcl commented on Explorer/Assets/Scripts/ECS/SceneLifeCycle/SceneDefinition/Systems/LoadSceneDefinitionListSystem.cs
> +            : base(world, cache, mutexSync, new NullBudgetProvider()) { }
Also if you really want to budget some specific loading systems (and their synchronous logic) it does not look sensible to include `BudgetProvider` in a base class.

2023-07-27 08:20 UTC, mikhail-dcl commented on Explorer/Assets/Scripts/Utility/CancellationTokenExtensions.cs
> +        public static void SafeCancelAndDispose(this CancellationTokenSource cancellationToken)
You won't need it if proposed changes are applied

2023-07-27 08:20 UTC, mikhail-dcl commented on Explorer/Assets/Scripts/ECS/Unity/GLTFContainer/Asset/Systems/CreateGltfAssetFromAssetBundleSystem.cs
> -            if (!instantiationThrottler.Acquire(assetBundleData.GameObjectNodes.Count))
Do you remember we were talking about removing the list and replacing it with a single object to exclude bias and not break each iteration by budgeting?

2023-07-27 11:17 UTC, dalkia commented on Explorer/Assets/Scripts/ECS/Profiling/ProfilingProvider.cs
> +                recorder.CopyTo(samples, samplesCount);
Changed! I saw the example in the Unity API (https://docs.unity3d.com/ScriptReference/Unity.Profiling.ProfilerRecorder.html); I missed the GetSample method

2023-07-28 08:29 UTC, mikhail-dcl approved these changes
GJ

2023-07-28 08:29 UTC, merged