Feat: Analytics integration
decentraland/unity-explorer pull request #1274
Opened 2024-06-18 09:59 UTC by popuz

## What does this PR change?

...

## How to test the changes?

1. Launch the explorer
2. ...

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

2024-07-09 11:02 UTC, mikhail-dcl requested changes

2024-07-09 11:02 UTC, mikhail-dcl commented on Explorer/Assets/DCL/UserInAppInitializationFlow/IReadOnlyRealFlowLoadingStatus.cs
>      public interface IReadOnlyRealFlowLoadingStatus
It's not read-only 😄

2024-07-09 11:02 UTC, mikhail-dcl commented on Explorer/Assets/DCL/Utilities/ReactiveProperties/ReadOnlyReactiveProperty.cs
> +    public class ReadOnlyReactiveProperty<T> : IReadOnlyReactiveProperty<T>
I think it is something strange that we will never need

2024-07-09 11:02 UTC, mikhail-dcl commented on Explorer/Assets/Scripts/Global/Static/StaticSceneLauncher.cs
> +            //
Please fix it

2024-07-11 11:52 UTC, anicalbano approved these changes
🟢 Reviewed by QA

2024-07-11 13:31 UTC, merged