feat: Locomotion
decentraland/unity-explorer pull request #151
Opened 2023-10-18 17:05 UTC by Kinerius

# Roadmap

**Must Have**

- [x] Gravity
- [x] Walking / Jogging / Running
- [x] Coyote time
- [x] Jumping
- [x] Jump Buffering
- [x] Jump Grace Time
- [x] Falling / Hard Falling / Hard Landing
- [x] Step Handling
- [x] Moving Platforms
- [x] Camera Effects
- [x] Animations
- [x] Mechanim Integration
- [ ] Playground

**Nice to have**

- [x] Slope Management
- [x] IK: Foot Placement
- [ ] Wall Sliding
- [ ] Wall Stomp
- [ ] Keyboard Mapping
- [ ] Controller Integration
- [ ] NFT hook
- [ ] SDK Integration
- [x] Developer Tools

**Expendables**

- [ ] Sounds
- [ ] Particle Effects
- [x] IK: Look At
- [ ] Stamina

2023-11-03 08:51 UTC, mikhail-dcl requested changes
The implementation looks gorgeous: very solid and clean 💪 
I just have several suggestions for further clean-up and tightening up

2023-11-03 08:51 UTC, mikhail-dcl commented on Explorer/Assets/DCL/AvatarRendering/AvatarShape/AvatarBase.cs
>          public void SetAsMainPlayer(bool isMainPlayer)
This piece was a pure draft, this feature is the right moment to change it. I don't mind if it is done a bit later but by the end of this feature.

2023-11-03 08:51 UTC, mikhail-dcl commented on Explorer/Assets/DCL/CharacterMotion/Animation/ApplyJumpState.cs
> +            in AvatarBase avatarBase,
I propose to create an interface for `AvatarBase.avatarAnimator` to enable Testability. And in both this method and `ApplyMovementBlend` you don't really need to couple with `MonoBeahviours` (especially considering `AvatarBase` is a draft

2023-11-03 08:51 UTC, mikhail-dcl commented on Explorer/Assets/DCL/CharacterMotion/Components/CharacterRigidTransform.cs
> +        public struct MovementVelocity
Can you check settings of your auto clean-up on commit? Mine changes the layout and removes redundant namespaces

2023-11-03 08:51 UTC, mikhail-dcl commented on Explorer/Assets/DCL/CharacterMotion/Platforms/SaveLocalPosition.cs
> +        public static void Execute(ref CharacterPlatformComponent platformComponent, Vector3 position)
I'd add `AggressiveInlining` hint just like you did for some other methods

2023-11-03 08:51 UTC, mikhail-dcl commented on Explorer/Assets/DCL/CharacterMotion/Platforms/SaveLocalRotation.cs
> +        public static void Execute(ref CharacterPlatformComponent platformComponent, Vector3 forward)
Here as well

2023-11-03 08:51 UTC, mikhail-dcl commented on Explorer/Assets/DCL/CharacterMotion/Platforms/SaveLocalRotation.cs
> +    public class SaveLocalRotation
You can make this class static

2023-11-03 08:51 UTC, mikhail-dcl commented on Explorer/Assets/DCL/CharacterMotion/Animation/ApplyJumpState.cs
> +            animationComponent.States.IsFalling = !rigidTransform.IsGrounded && rigidTransform.NonInterpolatedVelocity.y < -5f;
I believe we can move these magic constants to the settings

2023-11-03 08:51 UTC, mikhail-dcl commented on Explorer/Assets/DCL/CharacterMotion/Systems/CharacterPlatformSystem.cs
> +            bool hasHit = Physics.Raycast(ray, out RaycastHit hitInfo, 0.30f, PhysicsLayers.CHARACTER_ONLY_MASK);
Magic constant

2023-11-03 08:51 UTC, mikhail-dcl commented on Explorer/Assets/DCL/CharacterMotion/Systems/CharacterPlatformSystem.cs
> +                origin = transform.position + (Vector3.up * 0.15f),
Magic constant

2023-11-03 08:51 UTC, mikhail-dcl commented on Explorer/Assets/DCL/CharacterMotion/Systems/RotateCharacterSystem.cs
>          public override void Initialize()
Let's remove an empty method

2023-11-03 08:51 UTC, mikhail-dcl commented on Explorer/Assets/DCL/CharacterMotion/Velocity/ApplyAirDrag.cs
> +        private static Vector3 ApplyDrag(Vector3 vector, float drag, float deltaTime)
Don't we want to cover this logic with a Unit Test?

2023-11-03 08:51 UTC, mikhail-dcl commented on Explorer/Assets/DCL/CharacterMotion/Velocity/ApplySlopeModifier.cs
> +            float downwardsSlopeDistance = input.Kind == MovementKind.Run ? 0.55f : 0.45f;
Magic constant

2023-11-03 08:51 UTC, mikhail-dcl commented on Explorer/Assets/DCL/CharacterMotion/Velocity/ApplySlopeModifier.cs
> +            // Todo: cache
What did you want to cache here?

2023-11-03 08:51 UTC, mikhail-dcl commented on Explorer/Assets/DCL/CharacterMotion/Velocity/ApplyVelocityStun.cs
> +        public static void Execute(ref CharacterRigidTransform rigidTransform, in StunComponent stunComponent)
Aggressive Inlining

2023-11-03 08:51 UTC, mikhail-dcl commented on Explorer/Assets/DCL/Input/UIRaycaster.cs
> +            bool isInSafeAreaWidth = position.x < 15 || position.x > Screen.width - 15;
Can we give the constant a name?

2023-11-03 08:51 UTC, mikhail-dcl commented on Explorer/Assets/DCL/Time/Systems/UpdateTimeSystem.cs
> +            tickComponent.Time += dt;
I believe `deltaTime` is capped at a certain value so it's safer just to assign `UnityEngine.Time.time`

2023-11-03 08:51 UTC, mikhail-dcl commented on Explorer/Assets/Scripts/ECS/Abstract/SingleInstanceEntity.cs
> +                throw new Exception("Entity not found");
Can we add information about `query` to this Exception?

2023-11-03 18:06 UTC, Kinerius commented on Explorer/Assets/DCL/CharacterMotion/Velocity/ApplySlopeModifier.cs
> +            // Todo: cache
Probably an old comment

2023-11-13 10:15 UTC, mikhail-dcl approved these changes
Thank you, all concerns were addressed ❤️

2023-11-15 21:28 UTC, merged