Refactor: IAppArgs, marge CommandLineArgs and ApplicationParametersParser
decentraland/unity-explorer pull request #1848
Opened 2024-08-21 05:51 UTC by NickKhalow

## What does this PR change?

We had 2 objects with a very similar concern, it's unified under the single interface IAppArgs
...

## How to test the changes?

1. Launch the explorer
2. Play Happy path

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

2024-08-21 14:03 UTC, lorux0 approved these changes

2024-08-21 15:02 UTC, pravusjif requested changes
Left a minor request to synch with my recently merged small PR regarding a deep link update, the rest looks good!

2024-08-21 15:02 UTC, pravusjif commented on Explorer/Assets/Scripts/Global/Tests/EditMode/RealmLaunchSettingsShould.cs
> +using Global.AppArgs;
Is this import needed?

2024-08-23 07:32 UTC, NickKhalow commented on Explorer/Assets/Scripts/Global/AppArgs/ApplicationParametersParser.cs
>                  // Regex patch for MacOS removing the ':' from the realm parameter protocol
Done

2024-08-23 07:33 UTC, NickKhalow commented on Explorer/Assets/Scripts/Global/Tests/EditMode/RealmLaunchSettingsShould.cs
> +using Global.AppArgs;
Yes

2024-08-23 07:33 UTC, NickKhalow commented on Explorer/Assets/Scripts/Global/Dynamic/MainSceneLoader.cs
> +using Global.AppArgs;
Yes

2024-08-23 07:42 UTC, pravusjif approved these changes

2024-08-23 08:11 UTC, merged