add initial setup for AudioSource: Component-System, Plugin and respe…
decentraland/unity-explorer pull request #191
Opened 2023-12-11 14:26 UTC by popuz

…ctive registry

2024-01-10 12:36 UTC, anicalbano commented
✔️ Check the first iteration of the PR and looks correct. 
A comment regarding the sound performance is that, if we change realms after being inside the streaming world and then go back, the audio stops.
The video attached sounds low because of my own recording, but in world it sounds correct.

https://github.com/decentraland/unity-explorer/assets/139157886/ecb1f7e5-9a38-4a34-9058-16de156a1946

2024-01-10 13:46 UTC, mikhail-dcl requested changes
The flow looks absolutely correct but I found several things requiring a fix

2024-01-10 14:24 UTC, popuz commented on Explorer/Assets/DCL/PluginSystem/World/AudioSourcesPlugin.cs
> +            componentPoolsRegistry.AddGameObjectPool<AudioSource>();
I was thinking that this logic is handled in `CleanUpAudioSourceSystem` via `ReleaseOnEntityDestroy` (that also handles component removal). And `clip` nullifying is inside `AudioSourceComponent.Dispose`. As I checked, it works correctly now - released AudioSources inside pool have nothing assigned in the `clip` inspector field. 
Do I still need to nullify them here?

2024-01-10 15:27 UTC, mikhail-dcl commented on Explorer/Assets/DCL/PluginSystem/World/AudioSourcesPlugin.cs
> +            componentPoolsRegistry.AddGameObjectPool<AudioSource>();
```
if (poolsRegistry.TryGetPool(typeof(AudioSource), out IComponentPool componentPool))
                    componentPool.Release(component.Result);

                component.Dispose();
```
It's a bit obscure as dispose is called after releasing to the pool but in general it's fine.
I just don't expect that that the component is being manipulated **after** its internals are released to the pool

2024-01-10 17:08 UTC, popuz commented on Explorer/Assets/DCL/SDKComponents/AudioSources/AudioUtils.cs
> +            Debug.LogError($"Cannot detect AudioType. UrlName doesn't contain file extension!. Setting to {AudioType.UNKNOWN.ToString()}");
added ValidationTest to also prevent it in other classes. For now this test excludes `JsonUtils.cs`, `WorldSyncCommandBufferCollectionsPool.cs` and `Sentry` folder

2024-01-11 09:06 UTC, mikhail-dcl approved these changes

2024-01-11 10:33 UTC, merged