fix: show currently unread notifications badge
decentraland/unity-explorer pull request #2148
Opened 2024-09-24 08:55 UTC by lorenzo-ranciaffi

## What does this PR change?

Fix #1983 
...

## How to test the changes?

1. Launch the explorer
2. ...

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

2024-09-24 15:43 UTC, DafGreco reviewed
Windows verified 🟢 waiting for mac testing !

2024-09-25 07:17 UTC, davidejensen requested changes
Looks good, left 2 comments

2024-09-25 07:17 UTC, davidejensen commented on Explorer/Assets/DCL/Notifications/NotificationsMenu/NotificationsMenuController.cs
> +            view.unreadNotificationCounterText.text = unreadNotifications.ToString();
To String allocates a new string, you can improve it with the SetText provided by text mesh pro IIRC
```
 view.unreadNotificationCounterText.SetText("{0}", unreadNotifications);
```

2024-09-25 09:27 UTC, davidejensen approved these changes

2024-09-26 18:19 UTC, merged