Feat: sdk7 audio source url change
decentraland/unity-explorer pull request #260
Opened 2024-01-15 13:24 UTC by popuz

- add support to clip url change for audioSource component
- now AudioSource is played only if player is inside the scene (muted otherwise)

# How to test
- start experience and verify there is no any music playing from the start
- go to Dance Floor and verify music is only played if when you inside the dance floor

2024-01-18 09:12 UTC, mikhail-dcl requested changes
Implementation perfectly fits the purpose but I have just a few suggestions

2024-01-18 09:12 UTC, mikhail-dcl commented on Explorer/Assets/DCL/SDKComponents/AudioSources/AudioUtils.cs
> +        public static void CleanUp(this AudioSourceComponent component, World world, IStreamableCache<AudioClip, GetAudioClipIntention> cache, IComponentPool componentPool)
You should pass `AudioSourceComponent` by ref, otherwise changes made in `ForgetLoading` won't be reflected in the original component.

2024-01-18 09:12 UTC, mikhail-dcl commented on Explorer/Assets/DCL/SDKComponents/AudioSources/Systems/UpdateAudioSourceSystem.cs
> +                component.CleanUp(world, cache, audioSourcesPool);
Do you stop the current clip if it is cleaned up? I could not locate that logic

2024-01-18 09:54 UTC, mikhail-dcl approved these changes

2024-01-19 11:57 UTC, anicalbano approved these changes
✔️ QA reviewed! The sound is working as expected when entering the dance floor and no sound can be hear in other places of the scene.

2024-01-19 12:06 UTC, merged