feat: loading screen polishing
decentraland/unity-explorer pull request #274
Opened 2024-01-23 19:11 UTC by lorux0

2024-01-25 09:03 UTC, mikhail-dcl requested changes
Hey Nico, it will not work this way: you should respect empty scenes just like it's respected in the single-parcel version.
- You should modify ByParcelAsync(Vector2Int parcel, CancellationToken ct) to pass a readonly list instead. The endpoint already supports the list, currently it's requested with one parcel only
- You should filter out all empty parcels and create reports for non-empty ones. Otherwise, empty parcels will be never fullfilled

2024-01-26 12:34 UTC, anicalbano approved these changes
✔️ Reviewed and approved by QA

2024-01-29 11:12 UTC, mikhail-dcl requested changes

2024-01-29 11:12 UTC, mikhail-dcl commented on Explorer/Assets/DCL/SceneLoadingScreens/SceneLoadingScreenView.cs
> +                                 .AsyncWaitForCompletion()
You should not create an intermediate task and then convert it to `UniTask`. It creates an overhead: just use `DOTweenAsyncExtensions` directly (we already have a couple of use cases). You just need a `UniTask.DOTween` assembly for that.
Please consider changing all the occurences.

2024-01-29 11:12 UTC, mikhail-dcl commented on Explorer/Assets/DCL/SceneLoadingScreens/SceneLoadingScreenView.cs
> +                                        .AttachExternalCancellation(ct);
These extensions also have a built-in `CancellationToken` support so you don't need to work it around with `AttachExternalCancellation`. 
`AttachExternalCancellation` is general is a bad practive and should be used for code out of our control only: it does not clean-up any resources under the hood: it stops spininng the wrapped task only that may lead to resources leak.

2024-01-29 11:13 UTC, mikhail-dcl commented
Additionaly: are you sure that design-wise we should use `Teleport To Parcel` for Navmap instead of `Teleport To Spawn Point`?

2024-01-29 12:13 UTC, anicalbano commented
Re checked 🟢

2024-01-29 13:59 UTC, lorux0 commented
> Additionaly: are you sure that design-wise we should use `Teleport To Parcel` for Navmap instead of `Teleport To Spawn Point`?

Changed to teleport to spawn point (validated with product)

2024-01-29 14:04 UTC, mikhail-dcl approved these changes

2024-01-29 14:29 UTC, merged