fix: character trigger area has incorrect position
decentraland/unity-explorer pull request #2859
Opened 2024-11-22 08:31 UTC by fcolarich

## What does this PR change?

Fixes https://github.com/decentraland/unity-explorer/issues/2815

The issue here was that we are now spawning scenes at -10.000 in y coord, so when the assets are loaded, their cached positions are also set with that y and unless the transform changes we dont update it. AND the trigger areas copy their position each cycle from the CachedTransform in the TransformComponent.
The fix for that will go in another PR (which requires recursively update all the cached transforms of all the children of the scene after we set it in its definite position) as I found as simpler solution for this particular issue.
Parenting! By parenting the Trigger Area to the entity that in theory contains it, we ensure proper movement without needing any constant updating of the transform position to mimic any potential change in the parent's transform. After all, that's what parenting is for.

## How to test the changes?

Log into metadynelabs. The camera should be forced into 1st person and you should not see any other players around you.
That's all :)

2024-11-22 08:37 UTC, davidejensen approved these changes

2024-11-25 09:14 UTC, mikhail-dcl approved these changes

2024-11-28 13:57 UTC, pravusjif requested changes
character trigger areas (CameraModeArea and AvatarModifierArea SDK components) are still broken with these changes.

I find it easier to test with this dedicated test scene:
https://github.com/decentraland/sdk7-test-scenes/tree/main/scenes/9%2C99-modifier-areas

2024-11-28 18:24 UTC, pravusjif approved these changes

2024-11-28 19:12 UTC, anicalbano approved these changes
✔️ Both steps checked and working as expected, The camera view is correctly modified.

https://github.com/user-attachments/assets/fffd7a4d-4102-4c27-ad95-08e3f8e52e95


https://github.com/user-attachments/assets/8218eec0-9dc0-45df-90a3-5e8cda076490

2024-11-28 20:47 UTC, dalkia approved these changes

2024-11-29 19:11 UTC, merged