Feat: TexturesFuse fallback
decentraland/unity-explorer pull request #2983
Opened 2024-12-11 14:25 UTC by NickKhalow

Why?

In some cases user's hardware may be not reachable. Use default Unity's LoadImage method

## How to test the changes?

1. Launch the explorer
2. Play happy path

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

2024-12-11 18:33 UTC, m3taphysics approved these changes

2024-12-11 20:14 UTC, Ludmilafantaniella approved these changes
🟢 Smoke test was performed on Mac and Windows covering:
- Bckpack (wereables, emotes)
- Minigames (Minesweeper, Colorpop)
- Social Interactions (chat, emotes sync, wereables sync)
- Settings
- Teleport using chat command, map and GP Carrousel

No new issues were found.

2024-12-12 10:21 UTC, m3taphysics requested changes
Sergy from dApp craft is saying it is crashing

2024-12-17 10:44 UTC, m3taphysics commented
We disabled compression on windows for now as we need more investigation.

2024-12-17 10:44 UTC, closed without merging