feat: asset bundle fallback
decentraland/unity-explorer pull request #3008
Opened 2024-12-13 17:50 UTC by dalkia

## What does this PR change?

...

## How to test the changes?

1. Launch the explorer
2. ...

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

2025-01-02 17:40 UTC, AnsisMalins approved these changes
No "must fix" issues found. I'm not at all familiar with this code however.

2025-01-02 17:40 UTC, AnsisMalins commented on Explorer/Assets/DCL/Ipfs/LogIpfsRealm.cs
> +        }
Property getters should not have side effects. The log message suggests that there are side effects.

2025-01-27 12:04 UTC, DafGreco approved these changes
Main checks of this PR done on both platforms (Windows and Macos)

**Main check of the PR on Windows :**
Case 1: Ignored
`Comment: Could not test zone because of lack of Sepolia configuration. This first test will not be done`
Case 2 : ✅ 
`Comment : all scenes , building , roads and LODs load correctly. Teleporting to -129,-77 shows the correct message on the debug`
Case 3 : ✅ 
```
Comment : 
After disabling the feature flag I was able to do the following sanity check in order to see if everything behaves as expected :
```
- Camera functionality
- Map functionality
- Teleport (Dollhouse, The inn , Metadynelabs)
- Genesis plaza
- Genesis plaza's bar
- Skybox functionality
- Backpack (emotes and wearables)

**Main check of the PR on Macos:**

- Case 1 - Ignored
- Case 2: ✅ 
`All buildings and scenes seem to load normally and the message on the debug is the correct one when going to -129,-77`
- Case 3 : ✅ 

Sanity check made on the PR after the flag has been disabled :
- Map 
- Teleport
- Chat interactions
- Backpack
- Camera functionality
- Gallery
- Skybox functionality

2025-01-27 14:23 UTC, AnsisMalins requested changes

2025-01-27 15:19 UTC, dalkia commented on Explorer/Assets/DCL/Ipfs/EntityDefinitionGeneric.cs
> +        public string status;
It can, and it is now. Thx for the suggestion!

2025-01-27 15:27 UTC, AnsisMalins approved these changes

2025-01-27 17:12 UTC, merged