feat: sky controlls palen
decentraland/unity-explorer pull request #3020
Opened 2024-12-17 21:26 UTC by mihakrajnc

## What does this PR change?

Adds a popup to the left sidebar that opens sky controls which allow setting the current time of the skybox (and toggling whether it's dynamic or static).

Note that we currently don't have a hover / click animation for the sidebar button.

## How to test the changes?

1. Launch the explorer
2. Click on the new Sky button (left sidebar, bottom)
3. Make sure the skybox is correctly changed.
4. Make sure that the other buttons in the sidebar behave correctly.

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

2024-12-19 16:35 UTC, DafGreco approved these changes
Sanity check performed on both platforms ✅ 

**Checks done on both platforms :**
Sky change when jumping 
Sky change when being during the on boarding 
Sky change during metadynelabs
Sky change when playing mini-games
Multitapping between every shortcut + the sky button 
-
Teleport through command and through map 
Map 
Emotes 
Backpack
on boarding 
Metadynelabs 
Side bar

2025-01-07 16:05 UTC, fcolarich commented on Explorer/Assets/Scripts/Global/Dynamic/BootstrapContainer.cs
> +            if (!args.HasDebugFlag())
Same here with the debug, debug builds should not also be excluded from analytics?

2025-01-07 16:07 UTC, fcolarich commented on Explorer/Assets/Scripts/Global/Dynamic/BootstrapContainer.cs
> +            if (!args.HasDebugFlag())
NVM me, I just saw that this is included in the args... although it feels a bit hidden in some way? maybe it can be renamed to make it obvious that it includes both checks? 🤔
Otherwise at first glance it seems its only checking the flag...

2025-01-07 16:10 UTC, fcolarich commented on Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/StaticCommonTraitsPlugin.cs
> +            if (appArgs.HasDebugFlag())
I will paste the same correction I put below 😁 

> NVM me, I just saw that this is included in the args... although it feels a bit hidden in some way? maybe it can be renamed to make it obvious that it includes both checks? 🤔
> Otherwise at first glance it seems its only checking the flag...

2025-01-07 16:26 UTC, fcolarich commented on Explorer/Assets/DCL/StylizedSkybox/Scripts/Plugin/StylizedSkyboxPlugin.cs
>          }
This logic should probably be inside the controller, as the plugins are mostly used to setup the controllers and get/create/pass the dependencies for them. So you could pass the StylizedSkyboxSettingsAsset to the controller directly and from inside it subscribe to the events.

On the other hand, probably the StylizedSkyboxSettingsAsset should not have logic either (nor you should be writting to it). Normally the settings assets just contain references and fields that we can configure from the editor.
 
In this case I see you need to reuse it somewhere else to pass the values to the SkyboxSidebarController, I would suggest using an event bus to send the events from the SkyboxSidebarController to wherever else (so replacing the events inside the settings asset). You can send the event bus as dependency to both the SkyboxController and the SkyboxSidebarController.
For some examples you can check the BackpackEventBus or MapPinsEventBus, or any of these EventBuses xD

Yes its less straightforward than just using the settings asset, but its easier to undesrtand what's going on and cleaner in the end...
Lemme know if I can point you to any other example or whatever 😁

2025-01-07 16:27 UTC, fcolarich requested changes
I think the logic inside the SylizedSkyboxPlugin needs to be changed a bit as well as the use of the StylizedSkyboxSettingsAsset to send data between controllers.
Left a comment with some info about it, but just ping me if anything!!

2025-01-09 13:44 UTC, fcolarich approved these changes
Looks good!
Had my concerns about the scriptable object thing, but we discussed the possibilities already 👍

2025-01-09 17:14 UTC, merged