Feat: disk cache
decentraland/unity-explorer pull request #3030
Opened 2024-12-23 11:30 UTC by NickKhalow

## What does this PR change?

General cache to improve startup performance

## How to test the changes?

1. Launch the explorer
2. Play happy path, on second time textures and resources should load faster

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

2025-01-09 15:03 UTC, mikhail-dcl requested changes
The flow looks great 🔥 

I see no strategy implemented to clean-up `DiskCache`:

- I doubt we can ship without it as users will be endangered by ever-growing disk space occupied (and I can anticipate the number of reports with regard to it)
- I would go with something simple first: the upper limit (several GBs) for each domain, and LRU, it will be similar to how Unity's built-in Caching works

I would also consider data compression for writing to the drive but it can a next step

2025-01-09 16:16 UTC, NickKhalow commented
@mikhail-dcl 

_I would also consider data compression for writing to the drive but it can a next step_
There is the question what do we value more: user's disk space or user's loading time (I don't mention CPU, because we can do it on a background thread)

2025-01-09 16:21 UTC, NickKhalow commented on Explorer/Assets/Scripts/ECS/StreamableLoading/Cache/Disk/DiskCache.cs
> +            if (Directory.Exists(dirPath) == false) Directory.CreateDirectory(this.dirPath);
good point

2025-01-09 16:24 UTC, NickKhalow commented on Explorer/Assets/Scripts/ECS/StreamableLoading/Common/Systems/LoadSystemBase.cs
> +                diskCache ?? new IDiskCache<TAsset>.Null(),
done

2025-01-09 16:31 UTC, NickKhalow commented on Explorer/Assets/Scripts/ECS/StreamableLoading/Cache/Disk/IDiskCache.cs
> +        class InMemory : IDiskCache
removed, it's a temporal thing

2025-01-09 16:34 UTC, NickKhalow commented on Explorer/Assets/Scripts/ECS/StreamableLoading/Cache/Disk/HashNamings.cs
> +            var dictionary = new Dictionary<byte, string>();
Not in this case, CACHED_SYMBOLS is readonly and it won't allow to add the content

2025-01-09 16:36 UTC, NickKhalow commented on Explorer/Assets/Scripts/ECS/StreamableLoading/Common/Systems/LoadSystemBase.cs
> +                                ReportHub.LogError(ReportCategory.STREAMABLE_LOADING, $"Error putting cache content: {e.Message}")
it would, but the lambda is static and GetReportData is not. We can make it static accessible but it will involve an additional workaround

2025-01-10 10:44 UTC, mikhail-dcl commented on Explorer/Assets/Scripts/ECS/StreamableLoading/Cache/Disk/HashNamings.cs
> +            var dictionary = new Dictionary<byte, string>();
ah I see

2025-01-14 10:14 UTC, NickKhalow commented on Explorer/Assets/Scripts/ECS/StreamableLoading/Cache/Generic/IGenericCache.cs
> +            catch (Exception e) { return EnumResult<Option<T>, TaskError>.ErrorResult(TaskError.UnexpectedException, e.Message ?? string.Empty); }
Result<T> by design doesn't provide stack trace because Result<Error> is supposed as an expected case. But if we need it I can add a support for tracing in Result<T> with another PR

2025-01-14 19:13 UTC, NickKhalow commented on Explorer/Assets/Scripts/ECS/StreamableLoading/Textures/TextureDiskSerializer.cs
> +            await UniTask.SwitchToMainThread();
I tested, unity won't allow to call it from a background thread

2025-01-16 14:45 UTC, mikhail-dcl approved these changes
Thanks 👍 

In its current form we will be able to integrate it, but for the future I would consider the following:
- Different sub-directories for each type
- Different Disk quotes for each type
- Reliance of OS` `LastAccessTimeUtc` can be unreliable as it is not bound to the app itself

2025-01-23 16:29 UTC, DafGreco approved these changes
Sanity check performed on both platforms 🏁 

**Windows sanity check :**
- Teleport ✅  (Dollhouse / The inn / Metadynelabs)
- Camera functionality (Gallery) ✅ 
- Map✅ 
- Badges ✅ 
- Backpack (emotes and wearbales) ✅ 
- Notifications ✅ 
- Skybox functionality ✅ 

**Sanity check on macos :**

- Map ✅ 
- Backpack ✅ 
- Emotes✅ 
- Notifications✅ 
- Teleport ✅  (Dollhosue / the inn / Metadynelabs)
- camera functionality ✅ 
- Skybox ✅ 

No new issues were found during this sanity check

2025-01-23 17:25 UTC, m3taphysics approved these changes

2025-01-23 17:25 UTC, merged