Fix/profile publishing
decentraland/unity-explorer pull request #558
Opened 2024-04-10 18:14 UTC by NickKhalow

Issue is fixed, plus:

Refactor and simplify interfaces with InterfaceSegregationPrinciple
- EquippedWearable
- EquippedEmotes

ISelfProfile - Simplify dependencies where only this is required. No more passsing 2 objects: IProfileRepository and IWebIdentityCache in such cases

Logging for IProfileRepository, IpfsRealm and e.t.c

2024-04-11 14:53 UTC, mikhail-dcl requested changes
I only have minor things to mention

2024-04-11 15:39 UTC, NickKhalow commented on Explorer/Assets/DCL/Profiles/DataModels/ProfileJsonDto.cs
> +#nullable enable
I use `public ProfileJsonDto? FirstProfileDto()` there

If warnings are confusing I can add nullables to others

2024-04-11 15:42 UTC, NickKhalow commented on Explorer/Assets/DCL/Profiles/Self/SelfProfile.cs
> +        public UniTask<Profile?> ProfileAsync(CancellationToken ct) =>
with CQRS I prefer more accurate naming for Query, Get/Fetch/Obtain are generics

2024-04-12 07:47 UTC, mikhail-dcl approved these changes

2024-04-12 07:47 UTC, merged