Fix: sdk7 text shape alignment
decentraland/unity-explorer pull request #957
Opened 2024-05-06 12:32 UTC by popuz

## What does this PR change?
Main problem was due to the re-used values from the pooled TMPro object transforms, that were never reset.
- replicate most of the unity-renderer logic related to the protobuf values
- replaced logic by the usage of generic pool
- moved some logic into Systems and Extensions
- reused MaterialPropertyBlock 

## How to test the changes?

1. Launch the explorer
2. Goto dclexperience
3. Verify that text is on proper places. For example in Carousel - JUMP-IN, dates, titles
NOTE:  while most of texts will be on the proper place, you will also see text that should be hidden (but relative system need to be fixed, unrelated to this task)

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

2024-05-06 16:01 UTC, anicalbano reviewed
❔ The text look ok, taking in consideration what we see that should be hidden. The video shows that.
But regarding the glitches, I can still see them:
![image](https://github.com/decentraland/unity-explorer/assets/139157886/e41e01bc-8784-421d-a665-6035ae26897c)


https://github.com/decentraland/unity-explorer/assets/139157886/7b14d051-d2ee-4f8a-8203-3ab05bff59fa

2024-05-06 16:14 UTC, popuz commented
> ❔ The text look ok, taking in consideration what we see that should be hidden. The video shows that. But regarding the glitches, I can still see them: ![image](https://private-user-images.githubusercontent.com/139157886/328241055-e41e01bc-8784-421d-a665-6035ae26897c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwMTIyMTEsIm5iZiI6MTcxNTAxMTkxMSwicGF0aCI6Ii8xMzkxNTc4ODYvMzI4MjQxMDU1LWU0MWUwMWJjLTg3ODQtNDIxZC1hNjY1LTYwMzVhZTI2ODk3Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNlQxNjExNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMTAyNTdjYzA4MWFlMTZkMjU2MzcyMWYxNTQxMWU3NjI3NjM1YWVmYTE5YjVkZjQzNTYxODFkNGY0NzM4ODE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.M5JiR1iFGdWKdqnvaeu9v-BbkrVju-StGPlcnnwLw6w)
> 
>  06.05.2024_12.58.11_REC.mp4

Thanks, Ani. It is enough that there is no text at the glitched object, this object will be removed by content team soon

2024-05-06 20:08 UTC, anicalbano approved these changes

2024-05-07 08:39 UTC, mikhail-dcl requested changes

2024-05-07 08:39 UTC, mikhail-dcl commented on Explorer/Assets/DCL/PluginSystem/World/TextShapePlugin.cs
> -            settingsContainer.GetSettings<FontsSettings>().AsCached()
Can you please move `FontsSettings` to the settings of **this** plugin just like it's done for everything else?

2024-05-07 08:39 UTC, mikhail-dcl commented on Explorer/Assets/DCL/PluginSystem/World/TextShapePlugin.cs
> +            IComponentPool<TextMeshPro> textMeshProPool = componentPoolsRegistry.GetReferenceTypePool<TextMeshPro>();
Don't request the pool second time: `componentPoolsRegistry.AddGameObjectPool<TextMeshPro>();` already returns a reference to the pool: just introduce a `private readonly` field

2024-05-07 08:39 UTC, mikhail-dcl commented on Explorer/Assets/Scripts/ECS/Unity/Visibility/Systems/PrimitivesVisibilitySystem.cs
> +    [UpdateInGroup(typeof(SyncedPresentationSystemGroup))]
```suggestion
    [UpdateInGroup(typeof(SyncedSimulationSystemGroup))]
    [UpdateAfter(typeof(ComponentInstantiationGroup))]
```

WDYT?

2024-05-07 14:22 UTC, Kinerius approved these changes

2024-05-07 14:27 UTC, mikhail-dcl approved these changes

2024-05-07 15:45 UTC, merged